-- Insert 99 Verified Fully Funded Scholarships 2026
-- Batch 1 (50 scholarships) + Batch 2 (49 scholarships after removing duplicates)
-- These can be managed by admins through the admin portal at /admin-portal

-- STEP 1: Fix image_url constraint (make it optional)
-- This allows scholarships to be added without images
-- Images can be added later through the admin portal
ALTER TABLE opportunities ALTER COLUMN image_url DROP NOT NULL;

-- STEP 2: Insert all 99 unique scholarships
-- BATCH 1: First 50 Scholarships

INSERT INTO opportunities (title, description, type, organization, location, deadline, requirements, application_url, is_active) VALUES
('Manaaki New Zealand Scholarship',
'Full coverage including tuition, living allowance, travel, medical insurance, and establishment allowance. This is a prestigious government-funded scholarship for developing country nationals.',
'scholarship',
'NZ Ministry of Foreign Affairs',
'New Zealand',
'31 Mar 2026',
'Citizens of eligible developing countries in Asia, Pacific, Africa, Latin America; age 18+',
'https://www.nzscholarships.govt.nz/',
true),

('TaiwanICDF International Higher Education Scholarship',
'Comprehensive funding package covering full tuition, housing, round-trip airfare, insurance, textbooks, and monthly stipend for Bachelor''s, Master''s, and PhD programs.',
'scholarship',
'TaiwanICDF',
'Taiwan',
'15 Mar 2026',
'Citizens of TaiwanICDF partner countries; Bachelors/Masters/PhD',
'https://www.icdf.org.tw/wSite/ct?xItem=12505&ctNode=31562&mp=2',
true),

('DAAD EPOS Scholarship (Development-Related Postgraduate)',
'€992/month stipend plus tuition, health insurance, and travel allowance for development-related postgraduate studies in Germany.',
'scholarship',
'DAAD',
'Germany',
'15 Mar 2026',
'Developing country nationals; 2+ years work experience; Bachelor''s degree; max 6 years since graduation',
'https://www2.daad.de/deutschland/stipendium/datenbank/en/21148-scholarship-database/?detail=50076777',
true),

('Australia Awards Scholarships',
'Prestigious government scholarship covering full tuition, return air travel, establishment allowance, living expenses (CLE), and OSHC health cover. Priority given to Indo-Pacific region.',
'scholarship',
'Australian Government (DFAT)',
'Australia',
'30 Apr 2026',
'Citizens of eligible developing countries; Indo-Pacific priority; age 18+; not AUS/NZ citizen',
'https://www.dfat.gov.au/people-to-people/australia-awards/australia-awards-scholarships',
true),

('Chinese Government Scholarship (CSC)',
'Comprehensive scholarship covering tuition, accommodation, basic health insurance, and monthly stipend up to ¥3,500 for all academic levels.',
'scholarship',
'China Scholarship Council / MoE',
'China',
'30 Apr 2026',
'All nationalities; not Chinese citizen; Bachelors/Masters/PhD; strong academic record',
'https://studyinchina.csc.edu.cn',
true),

('KAUST Fellowship (King Abdullah University)',
'Elite STEM scholarship providing full tuition, $20,000–$30,000/year living allowance, on-campus housing, health & dental coverage, and relocation support.',
'scholarship',
'King Abdullah University of Science & Technology',
'Saudi Arabia',
'31 Mar 2026',
'All nationalities; Bachelor''s for MS; Master''s for PhD; STEM fields; IELTS 6.5 / TOEFL 79',
'https://admissions.kaust.edu.sa',
true),

('JJ/WBGSP — Joint Japan/World Bank Graduate Scholarship',
'Prestigious scholarship offering full tuition, monthly stipend, round-trip airfare, health insurance, and $600 travel allowance for development professionals.',
'scholarship',
'World Bank / Japan',
'Multi-country',
'29 May 2026',
'Developing country nationals; 3+ years development work; admitted to a JJ/WBGSP participating Master''s program',
'https://www.worldbank.org/en/programs/scholarships/jj-wbgsp',
true),

('GKS (Global Korea Scholarship) — Graduate',
'Comprehensive Korean government scholarship with tuition, Korean language training, monthly allowance KRW 1,000,000–1,500,000, round-trip airfare, settlement allowance, and health insurance.',
'scholarship',
'National Institute for International Education (NIIED)',
'South Korea',
'Apr 2026 (Univ. track)',
'All nationalities (NIIED eligible countries); under 40; Master''s/PhD/Research; CGPA 80%+',
'https://studyinkorea.go.kr',
true),

('DAAD Study Scholarship (Masters – All Disciplines)',
'€992/month stipend plus health/accident insurance, travel allowance, and study allowance for Master''s studies in Germany across all disciplines.',
'scholarship',
'DAAD',
'Germany',
'Check program deadline',
'Graduates from developing/emerging countries; Bachelor''s degree; above-average record; language proficiency (German/English)',
'https://www2.daad.de/deutschland/stipendium/datenbank/en/21148-scholarship-database/?detail=50026200',
true),

('DAAD STEM Scholarship',
'Specialized STEM scholarship offering €992/month stipend, health insurance, travel allowance, and one-off study allowance for Mathematics, Computer Science, Natural Sciences, and Engineering.',
'scholarship',
'DAAD',
'Germany',
'Check program deadline',
'Students from developing/emerging countries; Maths, Computer Science, Natural Sciences, Engineering',
'https://www2.daad.de/deutschland/stipendium/datenbank/en/21148-scholarship-database/?detail=57742130',
true),

('Stipendium Hungaricum — Hungary Government Scholarship',
'Full tuition coverage with HUF 43,700/month stipend, HUF 40,000/month accommodation allowance, and medical insurance for multiple academic levels.',
'scholarship',
'Hungarian Government',
'Hungary',
'15 Jan 2026 (CLOSED — results pending)',
'Citizens of sending partner countries (80+); Bachelor''s/Master''s/PhD/Non-degree; age 18+; must be nominated by sending country',
'https://stipendiumhungaricum.hu/apply/',
true),

('Swedish Institute Scholarship for Global Professionals (SISGP)',
'Prestigious scholarship covering full tuition, SEK 12,000/month living allowance, and SEK 15,000 travel grant for experienced professionals.',
'scholarship',
'Swedish Institute',
'Sweden',
'25 Feb 2026 (CLOSED — results pending)',
'Citizens of 33 eligible countries; 3,000+ hours work experience; leadership experience; admitted to eligible Swedish Master''s',
'https://si.se/en/apply/scholarships/swedish-institute-scholarships-for-global-professionals/',
true),

('MasterMind Scholarship (Flanders/Belgium)',
'€10,225/year grant plus tuition waiver (pay only ~€136.50), covering accommodation, insurance, and living expenses at Flemish institutions.',
'scholarship',
'Flemish Ministry of Education',
'Belgium',
'Varies by institution (spring 2026)',
'All nationalities (except Russian); admitted to master''s at Flemish institution; cannot be already enrolled in Flanders',
'https://www.studyinflanders.be/scholarships/master-mind-scholarships',
true),

('Erasmus Mundus Joint Masters (EMJM) — Multiple Programs',
'Prestigious European Commission scholarship offering €1,400/month living allowance, full tuition, travel allowance, and health insurance for 2-year joint Master''s programs across multiple European universities.',
'scholarship',
'European Commission',
'Europe (multi)',
'Varies by program (Jan–Apr 2026)',
'All nationalities worldwide; strong academic record; each program has specific requirements',
'https://erasmus-plus.ec.europa.eu/opportunities/opportunities-for-individuals/students/erasmus-mundus-joint-masters',
true),

('Mundus MAPP (Erasmus Mundus — Public Policy)',
'Full Erasmus Mundus package covering tuition, €1,400/month, health insurance, and travel for 2-year public policy program across 4 universities.',
'scholarship',
'Mundus MAPP Consortium / CEU',
'Europe (multi)',
'15 Apr 2026',
'All nationalities; strong academic record; interest in public policy/governance',
'https://www.mundusmapp.org/financial-aid/',
true),

('EMIMEP (Erasmus Mundus — Microelectronics/Photonics)',
'Full Erasmus Mundus package including tuition, €1,400/month, travel, and insurance for specialized Master''s in Microelectronics and Photonics.',
'scholarship',
'EMIMEP Consortium',
'Europe (multi)',
'Mar 2026 (application closed)',
'Bachelor''s in EE, Electronics, CS, Photonics or Physics; English proficiency CEFR B1+',
'https://www.erasmus-mundus.emimep.eu/admission-applications/',
true),

('Azerbaijan Government Scholarship',
'Full tuition, monthly stipend, accommodation, and health insurance for Preparatory, Bachelor''s, Master''s, PhD, and General Medicine programs.',
'scholarship',
'Government of Azerbaijan',
'Azerbaijan',
'15 Apr 2026',
'International students from eligible countries; Preparatory/Bachelors/Masters/PhD/General Medicine',
'https://tqdk.gov.az',
true),

('Romanian Government Scholarship (MFA)',
'Full tuition waiver, monthly stipend, and accommodation in student dormitories for non-EU citizens at all academic levels.',
'scholarship',
'Romanian Ministry of Foreign Affairs',
'Romania',
'15 Apr 2026',
'Non-EU citizens; all levels including medicine; no age limit for postgrad',
'https://www.mae.ro/en/node/10248',
true),

('Italian Government Scholarship (MAECI)',
'Monthly grant of €900 (undergraduate) or €1,100 (postgrad/research), Italian language course, and health insurance.',
'scholarship',
'Italian Ministry of Foreign Affairs',
'Italy',
'15 May 2026 (estimated)',
'Non-EU citizens or Italians abroad; Bachelor''s/Masters/PhD/Research/Italian language',
'https://borse.esteri.it',
true),

('Türkiye Bursları (Turkey Government Scholarship)',
'Comprehensive scholarship covering full tuition, monthly stipend up to TRY 1,600, return flight, health insurance, accommodation, and Turkish language course.',
'scholarship',
'Presidency for Turks Abroad and Related Communities',
'Turkey',
'20 Feb 2026 (CLOSED — results pending)',
'All nationalities (except Turkish); Bachelors/Masters/PhD; age limits apply by level',
'https://www.turkiyeburslari.gov.tr',
true),

('Heinrich Böll Foundation Scholarships',
'€934/month for Bachelor/Masters or €1,200/month for PhD students plus additional allowances, supporting students committed to green political values.',
'scholarship',
'Heinrich Böll Foundation',
'Germany',
'01 Mar 2026 (CLOSED — next: Sep 2026)',
'All nationalities; enrolled or planning to study in Germany; commitment to green political values; excellent academics',
'https://www.boell.de/en/foundation/scholarships',
true),

('Transilvania Academica Scholarship',
'Full tuition coverage and living stipend, renewable annually based on academic progress at Transilvania University of Brașov.',
'scholarship',
'Transilvania University of Brașov',
'Romania',
'10 Apr 2026',
'Non-EEA international students; Bachelor''s/Masters/PhD at Transilvania University',
'https://www.unitbv.ro/en/',
true),

('Swiss Government Excellence Scholarship',
'Elite scholarship providing full tuition waiver, CHF 1,920–3,500/month stipend, health insurance, round-trip airfare, and housing allowance.',
'scholarship',
'Swiss Confederation (SBFI)',
'Switzerland',
'Country-specific (typically Nov–Mar annually)',
'Citizens of eligible countries (varies by program); PhD/Postdoc/Research Master''s',
'https://www.sbfi.admin.ch/scholarships',
true),

('Danish Government Scholarship',
'Full tuition waiver plus monthly stipend for non-EU applicants, with support varying by institution.',
'scholarship',
'Danish Ministry of Higher Education',
'Denmark',
'Varies by university (Feb–Mar 2026)',
'Non-EU/EEA citizens; admitted to master''s at Danish university; strong academic profile',
'https://www.ufm.dk',
true),

('MISTRAL Excellence Scholarship (France)',
'€1,181/month allowance, travel reimbursement, health insurance, and tuition waiver at French grandes écoles.',
'scholarship',
'French Ministry of Higher Education',
'France',
'Oct–Dec 2026 (for next cycle)',
'Non-French nationals; under 30 (Masters), 35 (PhD); nominated by French institution',
'https://www.campusfrance.org',
true),

('Konrad-Adenauer-Stiftung (KAS) Scholarship',
'~€850–€1,200/month stipend, book allowance, and travel costs for students committed to political and civic engagement.',
'scholarship',
'Konrad-Adenauer-Stiftung',
'Germany',
'01 Jul 2026 (next cycle)',
'International students at German universities; above-average academics; commitment to political/civic engagement',
'https://www.kas.de/en/web/stipendien/international-scholarships',
true),

('MEXT Scholarship (Japanese Government)',
'Prestigious Japanese government scholarship covering full tuition, monthly allowance, round-trip airfare, and Japanese language training.',
'scholarship',
'Japanese Ministry of Education (MEXT)',
'Japan',
'Varies by embassy or university (Apr–Jun 2026)',
'All nationalities; Bachelor''s/Master''s/PhD/Research; age limits vary; strong academic record',
'https://www.mext.go.jp/en/policy/education/highered/title02/detail02/sdetail02/1373897.htm',
true),

('GKS (Global Korea Scholarship) — Undergraduate',
'Comprehensive undergraduate scholarship covering tuition up to KRW 5M/semester, KRW 900,000/month allowance, airfare, Korean language training, and settlement allowance.',
'scholarship',
'NIIED / Ministry of Education',
'South Korea',
'Oct 2025 — CLOSED (results Jan 2026; univ. track: Apr 2026)',
'71 eligible countries; under 25; high school diploma; CGPA 80%+; not Korean citizen',
'https://studyinkorea.go.kr',
true),

('Xi''an Jiaotong University CSC PhD Scholarship',
'Tuition waiver, accommodation, monthly allowance, and basic health insurance for PhD students at this leading Chinese university.',
'scholarship',
'Xi''an Jiaotong University',
'China',
'10 Apr 2026',
'All nationalities; not Chinese citizen; Master''s degree for PhD; strong research background',
'https://en.xjtu.edu.cn',
true),

('University of Chinese Academy of Sciences (UCAS) CSC Scholarship',
'Tuition waiver (¥40,000/yr PhD; ¥30,000/yr Masters), accommodation, health insurance, and monthly stipend at China''s premier research institution.',
'scholarship',
'UCAS / China Scholarship Council',
'China',
'Mar–Apr 2026',
'All nationalities; Bachelor''s for Masters, Master''s for PhD; application fee waived for CSC applicants',
'https://english.ucas.ac.cn',
true),

('ADB-Japan Scholarship Program (JSP)',
'Full tuition, monthly living allowance, housing, medical insurance, and travel for development professionals pursuing Master''s degrees.',
'scholarship',
'Asian Development Bank / Japan',
'Multi-country',
'Varies by program (Feb–Apr 2026)',
'Citizens of ADB borrowing member countries; 2+ years work experience; admitted to ADB-JSP partner university',
'https://www.adb.org/work-with-us/careers/adb-scholarship-program',
true),

('AfDB-Shanghai Ocean University Scholarship (SHOU)',
'Full tuition, accommodation, living allowance, and return airfare for African students pursuing Master''s degrees in marine and ocean sciences.',
'scholarship',
'African Development Bank / SHOU',
'China',
'Check official page',
'African Development Bank member country nationals; Bachelor''s in relevant field',
'https://www.afdb.org/en/careers/scholarships',
true),

('ICCR Scholarship (Indian Government)',
'Tuition waiver, monthly stipend, accommodation (hostel), and basic medical coverage at Indian universities.',
'scholarship',
'Indian Council for Cultural Relations',
'India',
'Varies by country (typically Jan–Mar 2026)',
'Citizens of eligible partner countries; Bachelor''s/Masters/PhD at participating Indian universities',
'https://a2ascholarships.iccr.gov.in',
true),

('KNB Scholarship (Indonesia Government)',
'Full tuition, monthly allowance, accommodation, health insurance, and return airfare for studies at Indonesian universities.',
'scholarship',
'Indonesian Ministry of Education',
'Indonesia',
'Varies (typically Mar–Apr 2026)',
'Citizens of developing countries with educational cooperation with Indonesia; Bachelor''s/Masters/PhD',
'https://knb.kemdikbud.go.id',
true),

('Brunei Darussalam Government Scholarship',
'Monthly allowance BND 650, accommodation, and full tuition waiver for ASEAN, Commonwealth, and OIC member countries.',
'scholarship',
'Brunei Ministry of Education',
'Brunei',
'Typically Apr–May 2026',
'ASEAN, Commonwealth, OIC member country citizens; Bachelors/Masters',
'https://www.moe.gov.bn/SitePages/Scholarship.aspx',
true),

('Chulalongkorn University Scholarship (Thailand)',
'100% tuition fees coverage plus monthly stipend and accommodation totaling 16,000 THB/month at Thailand''s most prestigious university.',
'scholarship',
'Chulalongkorn University',
'Thailand',
'May 2026 (Fall intake)',
'International students; Masters/PhD; May (Fall intake), Sep–Oct (Spring intake)',
'https://www.chula.ac.th/en/',
true),

('Government of Bhutan Scholarship (Royal Government)',
'Full coverage including tuition, living allowance, accommodation, and return airfare for Master''s studies in priority development fields.',
'scholarship',
'Royal Government of Bhutan',
'Bhutan',
'Varies (approx. Mar–Apr 2026)',
'Citizens of partner/friendly nations; Masters in priority development fields; must return to Bhutan after',
'https://www.moe.gov.bt',
true),

('KGSP/GKS University Track — Selected Universities (Korea)',
'Full tuition, monthly stipend, Korean language program, airfare, and insurance through direct university application.',
'scholarship',
'Korean universities via NIIED',
'South Korea',
'Apr 2026 (varies by university)',
'All nationalities; each university sets specific requirements; apply directly to university',
'https://studyinkorea.go.kr',
true),

('Commonwealth Distance Learning Scholarships 2026-27',
'Full tuition, monthly stipend, airfare, and dissertation grant for distance learning Master''s programs, allowing students to study from their home country.',
'scholarship',
'Commonwealth Scholarship Commission',
'United Kingdom',
'Check CSC portal (typically Jan–Mar)',
'Citizens of low and middle income Commonwealth countries; Bachelor''s equivalent degree',
'https://www.hbs.ac.uk/commonwealth-scholarships/',
true),

('QECS — Queen Elizabeth Commonwealth Scholarships',
'Full tuition, living allowance, travel, and health insurance for 2-year Master''s programs in low/middle-income Commonwealth countries.',
'scholarship',
'Association of Commonwealth Universities',
'Commonwealth (multi)',
'14 Jan 2026 (CLOSED — results pending)',
'Commonwealth citizens; studying in a different Commonwealth country; focus on development',
'https://www.acu.ac.uk/funding-opportunities/for-students/scholarships/queen-elizabeth-commonwealth-scholarships/',
true),

('Mastercard Foundation Scholars Program',
'Comprehensive funding covering full tuition, accommodation, living stipend, travel, health insurance, and leadership development for disadvantaged African youth.',
'scholarship',
'Mastercard Foundation / Partner Universities',
'Multi-country',
'Varies by university (Feb–May 2026)',
'Young Africans from economically disadvantaged backgrounds; at Mastercard Foundation partner universities',
'https://mastercardfdn.org/all/scholars/',
true),

('Gates Cambridge Scholarship',
'Elite scholarship covering full tuition, maintenance allowance, flights, visa, and family allowance for any subject at Cambridge University.',
'scholarship',
'Gates Foundation / University of Cambridge',
'United Kingdom',
'04 Dec 2025 (CLOSED; US citizens: Jan 2026)',
'All nationalities (non-UK); admitted to Cambridge full-time graduate program; leadership/academic excellence',
'https://www.gatescambridge.org/apply/',
true),

('Rhodes Scholarship',
'One of the world''s most prestigious scholarships covering full tuition at Oxford, living stipend, airfare, health insurance, and visa.',
'scholarship',
'Rhodes Trust / University of Oxford',
'United Kingdom',
'Country-specific (Jul–Oct 2025; CLOSED for 2026 entry)',
'Citizens of designated countries (32+); age limits vary (typically 18–25 for many countries); outstanding character/leadership',
'https://www.rhodeshouse.ox.ac.uk/scholarships/',
true),

('Knight-Hennessy Scholars (Stanford University)',
'Elite scholarship covering full tuition at Stanford, living stipend, travel, and enrichment activities fund for all graduate programs.',
'scholarship',
'Stanford University',
'USA',
'Check: Oct 2025 for 2026 entry (CLOSED)',
'All nationalities; admitted to Stanford graduate program; leadership; max 3.5 years since undergrad (typical)',
'https://knight-hennessy.stanford.edu/admission',
true),

('Fulbright Foreign Student Program',
'Comprehensive U.S. government scholarship covering full tuition, monthly stipend, airfare, and health insurance for Master''s, PhD, or research programs.',
'scholarship',
'U.S. Department of State',
'USA',
'Country-specific (Feb–Oct annually; many open now)',
'Citizens of Fulbright-eligible countries (~155 nations); vary by country; master''s/PhD/research',
'https://foreign.fulbrightonline.org/',
true),

('Vanier Canada Graduate Scholarship',
'Prestigious doctoral scholarship providing CAD $50,000/year for 3 years with research support.',
'scholarship',
'Government of Canada',
'Canada',
'Institutional deadlines Oct–Nov (CLOSED for 2026 entry)',
'Canadian/international students; enrolled in PhD at Canadian university; exceptional academic & leadership',
'https://vanier.gc.ca/',
true),

('Lester B. Pearson International Scholarship (University of Toronto)',
'Full tuition, books, incidentals, and full residence support for 4 years of undergraduate study at Canada''s top university.',
'scholarship',
'University of Toronto',
'Canada',
'Nominated by school (deadline Nov 2025 for 2026 — CLOSED)',
'International students nominated by their high school; outstanding academic/community profile',
'https://future.utoronto.ca/pearson/',
true),

('University of Melbourne Graduate Research Scholarships',
'Full tuition waiver, AUD $37,000/year stipend, relocation grant, and OSHC health insurance for research-based postgraduate programs.',
'scholarship',
'University of Melbourne',
'Australia',
'Rolling; major round Oct 2026',
'All nationalities; exceptional academic record; enrolled/enrolling in Melbourne PhD or Masters by Research',
'https://study.unimelb.edu.au/how-to-apply/graduate-research/fees-and-scholarships',
true),

('Macquarie University PhD International Scholarships (Graph Anomaly Detection)',
'Full tuition waiver, living stipend (AUD equivalent), and research support for specialized PhD research.',
'scholarship',
'Macquarie University',
'Australia',
'Open (rolling — apply ASAP)',
'All nationalities; strong CS/ML background; PhD enrollment at Macquarie',
'https://www.mq.edu.au/research/phd-and-research-degrees/scholarships',
true),

('SINGA Scholarship (Singapore)',
'Prestigious scholarship covering full tuition, SGD 2,000–2,500/month stipend, settling-in allowance, and conference grant for STEM PhD students.',
'scholarship',
'A*STAR / NUS / NTU / SUTD / SUSS',
'Singapore',
'Jun & Dec (next: Jun 2026)',
'All nationalities; science/engineering focus; admitted to PhD at partner institution',
'https://www.a-star.edu.sg/Scholarships/for-graduate-studies/singa-award',
true);

-- BATCH 2: Additional 49 Scholarships (1 duplicate removed)

INSERT INTO opportunities (title, description, type, organization, location, deadline, requirements, application_url, is_active) VALUES
('Aga Khan Foundation International Scholarship (AKF ISP)',
'Tuition and living expenses provided on 50% grant / 50% soft loan basis specifically designed for students from developing countries with no other funding source.',
'scholarship',
'Aga Khan Foundation',
'Multi-country',
'31 Mar 2026',
'Nationals of AKF partner countries (Afghanistan, Bangladesh, Egypt, India, Kenya, Kyrgyzstan, Madagascar, Mozambique, Pakistan, Syria, Tajikistan, Tanzania, Uganda); must have no other funding source; under 30 preferred',
'https://the.akdn/en/what-we-do/developing-human-capacity/education/international-scholarships',
true),

('EPFL Master Excellence Fellowship',
'Elite fellowship providing CHF 10,000/semester (up to CHF 40,000 total) and guaranteed student housing at one of Europe''s top technical universities.',
'scholarship',
'École Polytechnique Fédérale de Lausanne',
'Switzerland',
'31 Mar 2026 (round 2)',
'All nationalities; must apply to EPFL Master''s program; top 3% academic record; tick fellowship box in master''s application',
'https://www.epfl.ch/education/master/master-excellence-fellowships/',
true),

('University of Geneva Excellence Masters Fellowship',
'CHF 10,000–15,000/year for 3–4 semesters with no tuition fees at public universities, supporting excellence in science programs.',
'scholarship',
'University of Geneva (Faculty of Science)',
'Switzerland',
'28 Feb 2026 (CLOSED — results pending)',
'All nationalities; top 10% of bachelor''s class; applying to UNIGE MSc in science; not already enrolled at UNIGE',
'https://www.unige.ch/sciences/en/enseignements/formations/masters/excellencemasterfellowships',
true),

('Chevening Scholarship (UK Government) 2027-28',
'Prestigious UK government scholarship covering full tuition, monthly stipend, economy return airfare, arrival/departure allowances, visa fee, and extra travel grants.',
'scholarship',
'UK Foreign, Commonwealth & Development Office',
'United Kingdom',
'Oct 2026 (next cycle opens Aug 2026)',
'Citizens of 160+ eligible countries; 2+ years work experience; Bachelor''s equivalent to UK 2:1; leadership potential; must return home 2 years after',
'https://www.chevening.org/scholarships/',
true),

('MOFCOM Scholarship (China Ministry of Commerce)',
'Full tuition, on-campus accommodation, RMB 36,000/yr (Masters) or 42,000/yr (PhD) stipend, RMB 3,000 settlement, medical insurance, and round-trip airfare for development professionals.',
'scholarship',
'China Ministry of Commerce (MOFCOM) / CSC',
'China',
'31 May 2026',
'Developing country nationals under 45; Bachelor''s + 3 years work experience; government officials/senior managers preferred; English-taught programs',
'https://studyinchina.csc.edu.cn',
true),

('CAS-ANSO Scholarship (China Academy of Sciences)',
'Elite research scholarship providing full tuition waiver, RMB 3,000/month (Masters) or 6,000–7,000/month (PhD), health insurance, housing subsidy, and travel allowance.',
'scholarship',
'Alliance of International Science Organizations (ANSO) / CAS',
'China',
'31 Jan 2026 (CLOSED — results pending)',
'Non-Chinese citizens; Masters: born after 1 Jan 1996; PhD: born after 1 Jan 1991; STEM fields; English/Chinese proficiency; USTC or UCAS programs',
'https://www.anso.org.cn/programmes/talent/scholarship/',
true),

('Rotary Peace Fellowship',
'Comprehensive funding covering full tuition, housing, meals, travel, internship and field study expenses for 15–24 month Master''s programs at Rotary Peace Centers worldwide.',
'scholarship',
'The Rotary Foundation',
'Multi-country',
'~15 May 2026 (next cycle)',
'All nationalities; 3+ years relevant work experience (peace/development); Bachelor''s degree; English proficiency; at institutions in USA, UK, Japan, Australia, Sweden, Thailand, Uganda',
'https://www.rotary.org/en/our-programs/peace-fellowships',
true),

('HBKU Scholarship (Hamad Bin Khalifa University)',
'Full tuition waiver, QAR 5,000–7,500/month stipend, on-campus accommodation, annual return airfare, family housing (married students), and medical insurance.',
'scholarship',
'Hamad Bin Khalifa University / Qatar Foundation',
'Qatar',
'01 Feb 2026 (CLOSED — results pending)',
'All nationalities; strong GPA (3.0+); English proficiency (IELTS/TOEFL); Masters/PhD applicants; auto-considered at admission',
'https://www.hbku.edu.qa/en/scholarship',
true),

('France Eiffel Excellence Scholarship',
'Prestigious French government scholarship providing €1,200/month (Masters) or €2,100/month (PhD), round-trip airfare, health insurance, local transport reimbursement, and cultural access.',
'scholarship',
'French Ministry for Europe & Foreign Affairs / Campus France',
'France',
'08 Jan 2026 (CLOSED — results from 30 Mar 2026)',
'Non-French nationals; Masters: under 29 (born after Mar 1996); PhD: under 35 (born after Mar 1990); nominated by French institution; 7 priority fields',
'https://www.campusfrance.org/en/eiffel-excellence-scholarship-program',
true),

('ETH Zurich Excellence Scholarship (ESOP)',
'Elite scholarship providing CHF 12,000/semester living allowance plus full tuition waiver and mentorship at one of the world''s top technical universities.',
'scholarship',
'ETH Zurich',
'Switzerland',
'30 Nov 2026 (next cycle opens Nov 2026)',
'All nationalities; top 10% of bachelor''s program; applying to ETH Zurich Master''s; apply in first admission window only',
'https://ethz.ch/students/en/studies/financial/scholarships/excellencescholarship.html',
true),

('Politecnico di Milano International Fellowship',
'Full tuition waiver plus €7,000–10,000/year stipend and accommodation for 2-year Master''s programs in Engineering, Architecture, and Design.',
'scholarship',
'Politecnico di Milano',
'Italy',
'Mar–Apr 2026 (check specific program)',
'All non-Italian nationalities; excellent academic record; Master''s in Engineering, Architecture, Design; English proficiency',
'https://www.polimi.it/en/education/international-students',
true),

('Leiden University Excellence Scholarship (LExS)',
'€10,000–€15,000 tuition contribution or full scholarship with tuition waiver for top category students at one of the Netherlands'' oldest universities.',
'scholarship',
'Leiden University',
'Netherlands',
'01 Feb 2026 (CLOSED — next round Sep 2026)',
'Non-EU/EEA nationalities; top 10% of bachelor''s; applying to eligible Leiden Master''s program; strong motivation',
'https://www.universiteitleiden.nl/en/education/study-at-leiden-university/scholarships/leiden-university-excellence-scholarships',
true),

('Maastricht University Holland High Potential Scholarship',
'€21,500 covering tuition and stipend for one year, eligible for additional Netherlands/Maastricht merit scholarships.',
'scholarship',
'Maastricht University',
'Netherlands',
'01 Feb 2026 (CLOSED — next round Feb 2027)',
'Non-EU/EEA nationalities; top 10% of bachelor''s; admitted to selected UM Master''s programs; IELTS 7.0+',
'https://www.maastrichtuniversity.nl/education/scholarships/holland-high-potential-scholarship',
true),

('Humboldt Research Fellowship (Postdoctoral)',
'€2,670/month postdoc stipend plus family allowance, travel, and research support for 6–24 months of research in Germany.',
'scholarship',
'Alexander von Humboldt Foundation',
'Germany',
'Rolling (no fixed deadline)',
'All nationalities; PhD completed within last 12 years; above-average academic record; proposed German host institution',
'https://www.humboldt-foundation.de/en/apply/sponsorship-programmes/humboldt-research-fellowship',
true),

('Afrika Kommt! Fellowship (German Industry Program)',
'8-month internship at German company with 3 management training modules, German language course, visa, housing, study tour, and all expenses covered.',
'scholarship',
'Federation of German Industries (BDI) / DEG',
'Germany',
'CLOSED for 2026 cycle (next opens 2027)',
'African nationals (including North Africa) under 35; 2–5 years work experience; Bachelor''s degree; German or English proficiency',
'https://www.afrika-kommt.de',
true),

('Rosa Luxemburg Foundation Scholarship',
'€934/month for Bachelor/Masters or €1,334/month for PhD students plus book allowance and health insurance, supporting students committed to social justice.',
'scholarship',
'Rosa Luxemburg Stiftung',
'Germany',
'15 Apr 2026 & 15 Oct 2026',
'International students enrolled or admitted to German university; social justice/progressive values; merit + social commitment',
'https://www.rosalux.de/en/foundation/scholarships',
true),

('Friedrich Ebert Foundation Scholarship',
'€850 for Bachelor/Masters or €1,200/month for PhD plus book allowance, supporting students committed to social democratic ideals.',
'scholarship',
'Friedrich Ebert Stiftung',
'Germany',
'Apply year-round; decisions spring/fall',
'International students at German universities; commitment to social democratic ideals; academic excellence; participation in civic life',
'https://www.fes.de/en/international-scholarship-programme',
true),

('ARES Scholarships (Belgium – French Community)',
'Full tuition, monthly allowance ~€700, housing, round-trip airfare, and health insurance for Master''s and PhD programs at Belgian Francophone universities.',
'scholarship',
'Académie de Recherche et d''Enseignement Supérieur (ARES)',
'Belgium',
'Varies by program (Jan–Feb 2026 typically)',
'Citizens of partner developing countries (sub-Saharan Africa, Latin America, Asia, Middle East); under 40; Bachelor''s degree',
'https://www.ares-ac.be/en/cooperation-au-developpement/scholarships',
true),

('Government of Slovakia National Scholarship Program',
'Monthly stipend €200–€400 and accommodation subsidy for research stays, Master''s, and PhD programs at Slovak universities.',
'scholarship',
'Slovak Academic Information Agency (SAIA)',
'Slovakia',
'Oct 2025 & Apr 2026',
'All nationalities; Bachelor''s for Masters; Master''s for PhD; research / university background; apply through home country',
'https://www.scholarships.sk',
true),

('Polish Government Scholarship (NAWA Banach Program)',
'PLN 1,750/month stipend, accommodation, full tuition waiver, and insurance for 2-year Master''s programs relevant to developing countries.',
'scholarship',
'Polish National Agency for Academic Exchange (NAWA)',
'Poland',
'15 Apr 2026 (estimated)',
'Citizens of developing countries; Bachelor''s degree; Polish language courses included',
'https://nawa.gov.pl/en/students/foreign-candidates',
true),

('Finnish Government Scholarship Pool (CIMO/OKM)',
'€1,500/month stipend for 3–9 months supporting research/PhD/postdoc visits to Finnish universities.',
'scholarship',
'Finnish Ministry of Education and Culture',
'Finland',
'31 Jan 2026 (CLOSED — next cycle autumn 2026)',
'Doctoral or postdoctoral researchers; in countries with bilateral agreements; for research visits (not full degree programs)',
'https://www.oph.fi/en/services/scholarships-and-grants',
true),

('Prague Summer Schools Scholarship (Czech Republic)',
'Full tuition waiver, accommodation, stipend, and Czech language preparatory course for Master''s and PhD programs at Czech public universities.',
'scholarship',
'Czech Ministry of Education (MŠMT) / study.cz',
'Czech Republic',
'Sep 30 2025 (CLOSED for 2026 entry; next Sep 2026)',
'Developing country nationals (ODA list); Master''s or PhD level; nominated via home country embassy/ministry',
'https://www.dzs.cz/en/programme/czech-government-scholarships/',
true),

('Nalanda University Scholarship (India)',
'Full tuition waiver, monthly stipend INR 15,000–20,000, accommodation, and health coverage for 2-year MA programs in specialized fields.',
'scholarship',
'Nalanda University',
'India',
'Apr–May 2026 (varies by program)',
'International students from Asia and beyond; Masters in Buddhist Studies, Ecology & Environment, Historical Studies; IELTS/TOEFL required',
'https://nalandauniv.edu.in/admissions/financial-support/',
true),

('POSTECH International Graduate Scholarship (Korea)',
'Full tuition and KRW 1,000,000–1,500,000/month living allowance for STEM Master''s and PhD programs at Korea''s top science and technology university.',
'scholarship',
'Pohang University of Science and Technology',
'South Korea',
'Varies by semester (Feb & Aug rounds)',
'All nationalities; Bachelor''s for Masters; Master''s for PhD; strong STEM academic record; TOEFL/IELTS',
'https://international.postech.ac.kr/admission/scholarship/',
true),

('KAIST International Student Scholarship',
'Elite STEM scholarship covering full tuition, KRW 350,000–500,000/month living allowance, and health insurance at Korea''s premier research university.',
'scholarship',
'Korea Advanced Institute of Science & Technology',
'South Korea',
'Varies (Feb & Sep rounds; next: Sep 2026)',
'All nationalities; Bachelor''s for Masters; Master''s for PhD; strong STEM record; English proficiency (TOEFL/IELTS)',
'https://admission.kaist.ac.kr/intl-graduate/',
true),

('NTU Research Scholarship (Singapore)',
'SGD 2,000/month stipend plus tuition fee subsidy for research-based PhD students at Nanyang Technological University.',
'scholarship',
'Nanyang Technological University',
'Singapore',
'Rolling (major rounds: Dec 2025 & Jun 2026)',
'All nationalities; Bachelor''s or Master''s degree; admitted to NTU PhD research program; strong academic record',
'https://www.ntu.edu.sg/graduate-college/admissions-programmes/research-scholarships',
true),

('NUS Research Scholarship (Singapore)',
'SGD 2,000/month stipend, full tuition fee subsidy, health insurance, and research allowance for PhD students at National University of Singapore.',
'scholarship',
'National University of Singapore',
'Singapore',
'Rolling; major round Jan 2026 (CLOSED) & Jul 2026',
'All nationalities; Bachelor''s or Master''s; admitted to NUS research degree; strong GPA and research background',
'https://nus.edu.sg/registrar/prospective-students/graduate/research/research-scholarship',
true),

('Hokkaido University Japan-Asia Young Ambassador Scholarship',
'Full tuition, JPY 144,000/month living stipend, housing support, and travel allowance for Master''s and PhD programs at this leading Japanese university.',
'scholarship',
'Hokkaido University',
'Japan',
'Varies by intake (spring/fall 2026)',
'Citizens of Asia-Pacific countries; excellent academic record; English or Japanese proficiency',
'https://www.hokudai.ac.jp/en/news/scholarship/',
true),

('Waseda University Scholarship (Japan)',
'Full tuition waiver plus JPY 180,000/month allowance with accommodation support through various scholarship tracks.',
'scholarship',
'Waseda University',
'Japan',
'Varies by program (Jan & May rounds)',
'All nationalities; Masters/PhD applicants; strong academic record; English proficiency',
'https://www.waseda.jp/inst/cie/en/scholarship/',
true),

('University of Tokyo Presidential Fellowship',
'Elite fellowship covering full tuition, JPY 200,000/month living allowance, research budget, and health insurance at Japan''s top university.',
'scholarship',
'University of Tokyo (UTokyo)',
'Japan',
'Varies by department (Feb–Apr 2026)',
'All nationalities; exceptional research potential; admitted to UTokyo graduate program; English proficiency',
'https://www.u-tokyo.ac.jp/en/prospective-students/grad_programs.html',
true),

('University of British Columbia Graduate Award (Canada)',
'CAD 18,000/year stipend plus tuition supplement for research-based Master''s and PhD programs, renewable annually.',
'scholarship',
'University of British Columbia',
'Canada',
'Varies by department (Jan–Apr 2026)',
'All nationalities; enrolled in UBC research-based degree; strong academic record; must be admitted to program',
'https://www.grad.ubc.ca/awards',
true),

('University of Toronto School of Graduate Studies Fellowship',
'CAD 15,000–25,000/year plus tuition assistance for full-time Master''s and PhD programs, varying by department and track.',
'scholarship',
'University of Toronto',
'Canada',
'Varies by program (Jan–Feb 2026)',
'All nationalities; admitted to full-time graduate research program at UofT; strong academic record',
'https://www.sgs.utoronto.ca/awards/',
true),

('McGill University International Student Excellence Award',
'Full tuition differential covered plus CAD 10,000/year stipend for research-based Master''s or PhD programs, renewable based on performance.',
'scholarship',
'McGill University',
'Canada',
'Feb 2026 (department-specific)',
'International (non-Canadian) students; enrolled in McGill research-based program; top academic record',
'https://www.mcgill.ca/gps/funding/',
true),

('OAS Rowe Fund Scholarships (Organization of American States)',
'Full tuition, monthly stipend, health insurance, and accommodation for Master''s programs at approved OAS institutions throughout the Americas.',
'scholarship',
'Organization of American States (OAS)',
'Americas (multi)',
'Mar 2026 (varies by country)',
'Citizens of OAS member states (must be nationals of different country from host institution); Bachelor''s; English/Spanish/French/Portuguese proficiency',
'https://www.oas.org/en/scholarships/',
true),

('LASPAU Harvard-Affiliated Scholarship (Latin America)',
'Full tuition, stipend, living allowance, travel, and health insurance for Latin American students through Harvard-affiliated programs.',
'scholarship',
'LASPAU / Harvard University',
'USA / Latin America',
'Varies by program (Feb–Apr 2026)',
'Latin American & Caribbean citizens; Bachelor''s with excellent academic record; nominated by Latin American institution; partner program fields',
'https://laspau.harvard.edu/scholarships/',
true),

('African Union Commission Scholarship',
'Full tuition, living allowance, health insurance, and travel for Master''s programs at AU partner institutions across Africa.',
'scholarship',
'African Union Commission',
'Multi-Africa',
'Varies (check AU website; typically Apr–May 2026)',
'African nationals (AU member states); must pursue studies within Africa; Bachelor''s with minimum 3.0 GPA; under 35',
'https://au.int/en/ea/scholarships',
true),

('Pan African University Scholarship (PAU)',
'Full tuition waiver, monthly stipend, accommodation, health insurance, and travel grant for Master''s and PhD programs in STEM, governance, and social sciences.',
'scholarship',
'African Union / PAU',
'Africa (multi)',
'Jun 2026 (varies by PAU hub)',
'African nationals (all AU member states); Bachelor''s; strong academic record; STEM / governance / social sciences',
'https://pau-au.africa/scholarships',
true),

('TWAS-CNPq Fellowship (Brazil for Developing Countries)',
'BRL equivalent monthly stipend, round-trip airfare, and health insurance for PhD/Postdoc research in Brazil.',
'scholarship',
'TWAS / National Council for Scientific Development (CNPq)',
'Brazil',
'Varies (check TWAS website; typically Apr–Jul 2026)',
'Developing country nationals; hold PhD for postdoc; research at Brazilian institutions; STEM fields; Spanish or Portuguese proficiency helpful',
'https://twas.org/opportunity/twas-cnpq-postgraduate-fellowships-programme',
true),

('Monash University International Merit Scholarship (Australia)',
'AUD 10,000 tuition reduction per year for multiple years, supporting both undergraduate and Master''s programs based on merit.',
'scholarship',
'Monash University',
'Australia',
'Rolling (apply with admissions)',
'International students applying to Monash undergraduate or postgraduate degree; strong academic record (GPA equivalent 85%+)',
'https://www.monash.edu/scholarships/international',
true),

('ANU Chancellor''s International Scholarship',
'Full tuition waiver for undergraduate and postgraduate students based on merit at Australian National University.',
'scholarship',
'Australian National University',
'Australia',
'Rolling by program (Jan–Apr 2026)',
'International students (non-AU/NZ); undergraduate or graduate; strong academic excellence; ANU admissions required',
'https://www.anu.edu.au/study/scholarships/find-a-scholarship/anu-chancellors-international-scholarship',
true),

('University of Auckland International Excellence Award',
'Up to NZD 10,000/year tuition reduction for undergraduate and postgraduate programs based on merit, with automatic consideration.',
'scholarship',
'University of Auckland',
'New Zealand',
'Rolling (multiple rounds Nov–Mar annually)',
'International students admitted to UoA programs; strong academic record; automatically considered on application',
'https://www.auckland.ac.nz/en/study/scholarships-and-awards.html',
true),

('TWAS-SISSA Sandwich PhD Fellowship (Italy)',
'€900–1,200/month stipend, accommodation at SISSA, travel, and health insurance for 6–12 months research visit to Italy.',
'scholarship',
'TWAS / SISSA Trieste',
'Italy',
'Mar–Apr 2026 (check TWAS website)',
'Developing country nationals; PhD student enrolled at home country institution; natural sciences/mathematics research',
'https://twas.org/opportunity/twas-sissa-sandwich-training-educational-programme-step',
true),

('ICTP Fellowships (Trieste, Italy)',
'Monthly stipend, accommodation subsidy, travel to Trieste, and health insurance for scientists from developing countries conducting research in physics, mathematics, and earth system sciences.',
'scholarship',
'International Centre for Theoretical Physics (ICTP)',
'Italy / Multi',
'Varies by program (rolling; check ictp.it)',
'Scientists from developing countries; PhD (for research fellowships); physics/mathematics/earth system sciences',
'https://www.ictp.it/programs/fellowships.aspx',
true),

('KOICA Scholarship (Korean Int''l Cooperation Agency)',
'Full tuition, KRW 900,000/month living allowance, round-trip airfare, accommodation, health insurance, and settling-in allowance for development-sector professionals.',
'scholarship',
'Korea International Cooperation Agency (KOICA)',
'South Korea',
'Varies by country (typically Jan–Mar 2026)',
'Citizens of KOICA partner countries (ODA recipients); 2+ years work experience; Bachelor''s; nominated by home government',
'https://www.koica.go.kr/sites/koica_en/scholarship',
true),

('Russian Government Scholarship',
'Full tuition waiver, monthly stipend (~RUB 1,500–3,000), and accommodation in dormitory for Bachelor''s, Master''s, PhD, and Residency programs.',
'scholarship',
'Russian Ministry of Education (Rossotrudnichestvo)',
'Russia',
'Varies by country (apply through Russian embassy; typically Feb–Mar 2026)',
'Citizens of countries with bilateral agreements; Russian language proficiency required for most programs; various age limits',
'https://education-in-russia.com',
true),

('Brazil Scientific Mobility Program (PEC-PG Scholarship)',
'BRL monthly stipend, health insurance, and one-way airfare for Master''s and PhD programs at Brazilian universities.',
'scholarship',
'Brazilian Government / CAPES / CNPq',
'Brazil',
'Varies by country (typically Mar–Jun 2026)',
'Citizens of developing countries with bilateral agreements; Bachelor''s for Masters; Master''s for PhD; Portuguese language competency',
'https://www.gov.br/capes/pt-br/acesso-a-informacao/acoes-e-programas/bolsas/bolsas-no-exterior/programas-de-bolsas/pec-pg',
true),

('HKPFS — Hong Kong PhD Fellowship Scheme',
'Prestigious fellowship providing HKD 27,600/month stipend (≈USD 3,500), HKD 13,800 conference/research travel for up to 4 years of PhD study.',
'scholarship',
'Research Grants Council (RGC), Hong Kong',
'Hong Kong SAR',
'01 Dec 2025 (CLOSED — results pending; next Dec 2026)',
'All nationalities; exceptional academic record; PhD applicant at any UGC-funded HK institution; all disciplines',
'https://cerg1.ugc.edu.hk/hkpfs/index.html',
true),

('Orange Knowledge Programme (Netherlands / OKP)',
'Full tuition, living allowance, round-trip travel, insurance, and visa for short courses and Master''s degrees in development-related fields.',
'scholarship',
'Dutch Ministry of Foreign Affairs / Nuffic',
'Netherlands',
'Varies by institution (Jan–Apr 2026 rounds)',
'Citizens of 54 OKP eligible countries; 3+ years work experience; nominated by employer; development-sector professional',
'https://www.studyinholland.nl/scholarships/highlighted-scholarships/orange-knowledge-programme',
true),

('Islamic Development Bank Scholarship (IsDB)',
'Comprehensive funding covering full tuition, monthly stipend, accommodation, travel, and health insurance for undergraduate, Master''s, PhD, and merit scholarships.',
'scholarship',
'Islamic Development Bank Group',
'Multi-country',
'Varies (typically Mar–May 2026; check IsDB portal)',
'Nationals of IsDB member countries; Muslim students; academic merit; priority to STEM and development fields',
'https://www.isdb.org/scholarships',
true);

-- Note: The above SQL covers all 99 unique scholarships from both batches (1 duplicate removed).
-- All scholarships are set to is_active = true by default.
-- Admins can edit, hide/show, or delete any scholarship through the admin portal at /admin-portal
-- Image URLs are left as NULL - admins can add images later through the admin interface if desired.
--
-- REMOVED DUPLICATE: Heinrich Böll Foundation (was listed in both batches, kept the comprehensive Batch 1 entry)
