export interface CertificateProvider {
  id: string;
  name: string;
  description: string;
  logo: string;
  color: string;
  courseCount: string;
  category: string;
  url: string;
  features: string[];
  courses: { name: string; url: string }[];
}

export const certificateProviders: CertificateProvider[] = [
  {
    id: "google",
    name: "Google",
    description: "Over 450 free certificates and badges across Android Development, Google Analytics, Google Cloud, Digital Marketing, and more.",
    logo: "https://www.classcentral.com/images/logos/providers/google-sq.png",
    color: "#4285F4",
    courseCount: "450+",
    category: "Technology",
    url: "https://www.classcentral.com/report/free-google-certifications/",
    features: ["Industry-recognized certifications", "Self-paced learning", "Free digital badges", "Beginner to advanced levels"],
    courses: [
      { name: "Google Analytics Certification", url: "https://www.classcentral.com/course/skillshop-google-analytics-certification-126436" },
      { name: "Google Ads Search Certification", url: "https://www.classcentral.com/course/google-ads-search-certification-98564" },
      { name: "Introduction to Generative AI", url: "https://www.classcentral.com/course/introduction-to-generative-ai-199878" },
      { name: "Google Ads Video Certification", url: "https://www.classcentral.com/course/skillshop-google-ads-video-certification-86242" },
      { name: "Google Play Store Listing Certificate", url: "https://playacademy.withgoogle.com/certificate/" },
      { name: "Introduction to Large Language Models", url: "https://www.classcentral.com/course/introduction-to-large-language-models-199879" },
    ]
  },
  {
    id: "linkedin-learning",
    name: "LinkedIn Learning",
    description: "115 learning paths and 400+ individual courses with free certificates — over 470 hours of free online learning in business, design, and technology.",
    logo: "https://www.classcentral.com/images/logos/providers/linkedin-sq.png",
    color: "#0A66C2",
    courseCount: "470+ hrs",
    category: "Professional Development",
    url: "https://www.classcentral.com/report/linkedin-learning-free-learning-paths/",
    features: ["Professional certificates", "Learning paths", "Industry expert instructors", "Add to LinkedIn profile"],
    courses: [
      { name: "Career Essentials in Generative AI by Microsoft", url: "https://www.classcentral.com/course/linkedin-learning-career-essentials-in-generative-ai-by-microsoft-and-linkedin-301988" },
      { name: "Professional Soft Skills Learning Pathway", url: "https://www.classcentral.com/course/linkedin-learning-professional-soft-skills-learning-pathway-101219" },
      { name: "Project Management Foundations", url: "https://www.classcentral.com/course/linkedin-learning-project-management-foundations-31092" },
      { name: "Communication Foundations", url: "https://www.classcentral.com/course/linkedin-learning-communication-foundations-29764" },
      { name: "Critical Thinking for Better Judgment", url: "https://www.classcentral.com/course/linkedin-learning-critical-thinking-for-better-judgment-and-decision-making-29866" },
      { name: "Entrepreneurship Foundations", url: "https://www.classcentral.com/course/linkedin-learning-entrepreneurship-foundations-29992" },
    ]
  },
  {
    id: "harvard",
    name: "Harvard University",
    description: "10 world-renowned CS50 courses with free certificates including Computer Science, AI, Web Programming, Python, and Cybersecurity.",
    logo: "https://www.classcentral.com/images/logos/providers/harvard-sq.png",
    color: "#A51C30",
    courseCount: "10",
    category: "Computer Science",
    url: "https://www.classcentral.com/report/harvard-cs50-guide/",
    features: ["Ivy League education", "World's most popular MOOC", "Free certificate via OCW", "6M+ enrollments"],
    courses: [
      { name: "CS50's Introduction to Computer Science", url: "https://www.classcentral.com/course/edx-cs50-s-introduction-to-computer-science-442" },
      { name: "CS50's Web Programming with Python & JavaScript", url: "https://cs50.harvard.edu/web/" },
      { name: "CS50's Introduction to AI with Python", url: "https://cs50.harvard.edu/ai/" },
      { name: "CS50's Introduction to Programming with Python", url: "https://cs50.harvard.edu/python/" },
      { name: "CS50's Introduction to Cybersecurity", url: "https://www.classcentral.com/course/cybersecurity-harvard-university-cs50-s-introduct-152356" },
      { name: "CS50's Introduction to Databases with SQL", url: "https://cs50.harvard.edu/sql/" },
    ]
  },
  {
    id: "stanford-med",
    name: "Stanford Medicine",
    description: "200+ medical courses with free certificates and CME credit. Includes podcasts, webinars, and full online courses.",
    logo: "https://www.classcentral.com/images/logos/providers/stanford-sq.png",
    color: "#8C1515",
    courseCount: "200+",
    category: "Healthcare",
    url: "https://www.classcentral.com/report/stanford-med-free-certificates/",
    features: ["CME credit available", "Formal transcript from Stanford", "Expert medical faculty", "Free podcasts & webinars"],
    courses: [
      { name: "Health Across the Gender Spectrum", url: "https://online.stanford.edu/courses/som-ycme0034-health-across-gender-spectrum" },
      { name: "Stanford Medcast Podcast", url: "https://stanford.cloud-cme.com/course/courseoverview?P=0&EID=53767" },
      { name: "Intro to Food and Health", url: "https://www.classcentral.com/report/stanford-med-free-certificates/" },
    ]
  },
  {
    id: "open-university",
    name: "Open University (OpenLearn)",
    description: "900+ free online courses with free certificates of completion and badges across arts, business, science, technology, and more.",
    logo: "https://www.classcentral.com/images/logos/providers/openuniversity-sq.png",
    color: "#006FE8",
    courseCount: "900+",
    category: "Academic",
    url: "https://www.classcentral.com/report/open-university-free-certificates/",
    features: ["University-level quality", "Wide subject range", "Free certificates & badges", "Self-paced learning"],
    courses: [
      { name: "Everyday English 1", url: "https://www.classcentral.com/course/openlearn-everyday-english-1-content-section-over-95837" },
      { name: "Information Security", url: "https://www.classcentral.com/course/openlearn-science-maths-technology-information-se-96035" },
      { name: "Getting Started on Classical Latin", url: "https://www.classcentral.com/course/openlearn-history-the-arts-getting-started-on-cla-95485" },
      { name: "Microbes – Friend or Foe?", url: "https://www.classcentral.com/course/openlearn-nature-environment-microbes-friend-or-f-95957" },
      { name: "The Business of Football", url: "https://www.classcentral.com/course/openlearn-the-business-football-content-section-o-95860" },
      { name: "Introducing Social Care and Social Work", url: "https://www.classcentral.com/course/openlearn-introducing-social-care-and-social-work-295801" },
    ]
  },
  {
    id: "semrush",
    name: "Semrush Academy",
    description: "90+ free courses on marketing and SEO with free certificates. Topics include AI marketing, technical SEO, content strategy, and more.",
    logo: "https://www.classcentral.com/images/logos/providers/semrush-sq.png",
    color: "#FF642D",
    courseCount: "90+",
    category: "Digital Marketing",
    url: "https://www.classcentral.com/provider/semrush-academy?free-certificate=true",
    features: ["Industry-leading SEO tools", "Expert instructors", "Practical certifications", "Marketing focus"],
    courses: [
      { name: "Become an AI-Powered Marketer", url: "https://www.classcentral.com/course/ai-for-marketing-course-289814" },
      { name: "On-Page and Technical SEO Course", url: "https://www.classcentral.com/course/semrush-on-page-and-technical-seo-course-62159" },
      { name: "Content-Led SEO with Brian Dean", url: "https://www.classcentral.com/course/semrush-content-led-seo-course-with-brian-dean-97641" },
      { name: "How to Optimize for Mobile: CRAFT of Mobile SEO", url: "https://www.classcentral.com/course/craft-of-mobile-seo-278241" },
    ]
  },
  {
    id: "codesignal",
    name: "CodeSignal Learn",
    description: "2000+ courses and learning paths with free certificates in coding, AI & ML, data science, interview prep, and more.",
    logo: "https://www.classcentral.com/images/logos/providers/codesignal-sq.png",
    color: "#6C47FF",
    courseCount: "2000+",
    category: "Programming",
    url: "https://www.classcentral.com/provider/codesignal",
    features: ["Massive course library", "Coding interview prep", "AI & ML focus", "Beginner to advanced"],
    courses: [
      { name: "Programming Foundations with Python", url: "https://www.classcentral.com/course/codesignal-programming-foundations-with-python-357794" },
      { name: "Four-Week Coding Interview Prep in Python", url: "https://www.classcentral.com/course/codesignal-four-week-coding-interview-prep-in-python-361276" },
      { name: "Understanding LLMs and Basic Prompting", url: "https://www.classcentral.com/course/codesignal-understanding-llms-and-basic-prompting-techniques-357769" },
      { name: "Introduction to HTML", url: "https://www.classcentral.com/course/codesignal-introduction-to-html-357717" },
      { name: "JavaScript Programming for Beginners", url: "https://www.classcentral.com/course/codesignal-javascript-programming-for-beginners-361232" },
      { name: "Getting Started with Java", url: "https://www.classcentral.com/course/codesignal-getting-started-with-java-357726" },
    ]
  },
  {
    id: "freecodecamp",
    name: "freeCodeCamp",
    description: "1000+ hours of free coding certifications in web development, data science, Python, JavaScript, and more. Nonprofit learning platform.",
    logo: "https://www.classcentral.com/images/logos/providers/freecodecamp-sq.png",
    color: "#0A0A23",
    courseCount: "1000+ hrs",
    category: "Programming",
    url: "https://www.classcentral.com/provider/freecodecamp",
    features: ["100% free forever", "Interactive coding challenges", "Industry-recognized certifications", "Huge community"],
    courses: [
      { name: "Responsive Web Design", url: "https://www.classcentral.com/course/freecodecamp-responsive-web-design-v9-515064" },
      { name: "JavaScript Certification", url: "https://www.classcentral.com/course/freecodecamp-javascript-v9-515065" },
      { name: "Python Certification", url: "https://www.classcentral.com/course/freecodecamp-python-v9-515067" },
      { name: "Data Analysis with Python", url: "https://www.classcentral.com/course/freecodecamp-data-analysis-with-python-34066" },
      { name: "Foundational C# with Microsoft", url: "https://www.classcentral.com/course/freecodecamp-foundational-c-sharp-with-microsoft-284467" },
      { name: "Back End Development and APIs", url: "https://www.classcentral.com/course/freecodecamp-back-end-development-and-apis-34063" },
    ]
  },
  {
    id: "digital-marketing",
    name: "Digital Marketing Certificates",
    description: "300+ free digital marketing certificates and badges from Google, Meta, X (Twitter), Semrush, HubSpot, and more.",
    logo: "https://www.classcentral.com/images/logos/providers/hubspot-sq.png",
    color: "#FF6B35",
    courseCount: "300+",
    category: "Digital Marketing",
    url: "https://www.classcentral.com/report/free-digital-marketing-certificates/",
    features: ["Multi-platform certifications", "SEO, SEM, social media", "Industry-recognized", "Practical skills"],
    courses: [
      { name: "Google Analytics Certification", url: "https://www.classcentral.com/course/skillshop-google-analytics-certification-126436" },
      { name: "Meta Certified Digital Marketing Associate", url: "https://www.facebook.com/business/learn/certification/exams/100-101-exam" },
      { name: "SEO Certification Course (HubSpot)", url: "https://www.classcentral.com/course/seo-training-66293" },
      { name: "Inbound Marketing Certification (HubSpot)", url: "https://www.classcentral.com/course/hubspot-inbound-marketing-course-98574" },
      { name: "Content Marketing Principles for Business", url: "https://www.classcentral.com/course/content-marketing-principles-for-business-278250" },
    ]
  },
  {
    id: "futurelearn",
    name: "FutureLearn",
    description: "70+ online courses with free digital upgrade and Certificate of Achievement from top universities and organizations.",
    logo: "https://www.classcentral.com/images/logos/providers/futurelearn-sq.png",
    color: "#E32D7E",
    courseCount: "70+",
    category: "Academic",
    url: "https://www.classcentral.com/report/futurelearn-free-certificates/",
    features: ["Top university partners", "Digital Certificate of Achievement", "Unlimited access", "Expert educators"],
    courses: [
      { name: "Digital Skills: Digital Marketing (Accenture)", url: "https://www.classcentral.com/course/digital-skills-digital-marketing-9778" },
      { name: "Digital Skills: Artificial Intelligence (Accenture)", url: "https://www.classcentral.com/course/artificial-intelligence-16995" },
      { name: "Digital Skills: User Experience (Accenture)", url: "https://www.classcentral.com/course/digital-skills-user-experience-9780" },
      { name: "Social Learning and Collaboration in School (Lego)", url: "https://www.classcentral.com/course/social-learning-collaboration-in-school-56657" },
    ]
  },
  {
    id: "ibm",
    name: "IBM",
    description: "100+ courses and 30+ learning paths with free badges and certificates in data science, AI, cloud computing, blockchain, and more.",
    logo: "https://www.classcentral.com/images/logos/providers/ibm-sq.png",
    color: "#0062FF",
    courseCount: "100+",
    category: "Technology",
    url: "https://cognitiveclass.ai/courses",
    features: ["Cognitive Class platform", "Virtual lab environment", "Industry-recognized badges", "Credly integration"],
    courses: [
      { name: "Accelerating Deep Learning with GPUs", url: "https://www.classcentral.com/course/cognitive-class-accelerating-deep-learning-with-gpus-118534" },
      { name: "Introduction to Open Source", url: "https://www.classcentral.com/course/cognitive-class-introduction-to-open-source-118537" },
      { name: "Text Analytics 101", url: "https://www.classcentral.com/course/cognitive-class-text-analytics-101-118546" },
      { name: "Applied Data Science with R", url: "https://cognitiveclass.ai/learn/data-science-r" },
      { name: "Big Data Foundations", url: "https://cognitiveclass.ai/learn/big-data" },
    ]
  },
  {
    id: "matlab",
    name: "MATLAB (MathWorks)",
    description: "24 free online courses with free certificates covering MATLAB programming, machine learning, Simulink, signal processing, and more.",
    logo: "https://www.classcentral.com/images/logos/providers/mathworks-sq.png",
    color: "#E16737",
    courseCount: "24",
    category: "Engineering",
    url: "https://www.classcentral.com/report/matlab-free-certificates/",
    features: ["Official MathWorks training", "Free certificate of completion", "Progress reports", "Hands-on exercises"],
    courses: [
      { name: "MATLAB Onramp", url: "https://www.classcentral.com/course/matlab-onramp-94369" },
      { name: "Machine Learning Onramp", url: "https://www.classcentral.com/course/machine-learning-onramp-94372" },
      { name: "Simulink Onramp", url: "https://www.classcentral.com/course/simulink-onramp-94370" },
      { name: "Image Processing Onramp", url: "https://www.classcentral.com/course/image-processing-onramp-94375" },
      { name: "Signal Processing Onramp", url: "https://www.classcentral.com/course/signal-processing-onramp-94376" },
      { name: "Reinforcement Learning Onramp", url: "https://www.classcentral.com/course/reinforcement-learning-onramp-94374" },
    ]
  },
  {
    id: "kaggle",
    name: "Kaggle",
    description: "Free data science courses with certificates covering Python, SQL, machine learning, deep learning, computer vision, and more.",
    logo: "https://www.classcentral.com/images/logos/providers/kaggle-sq.png",
    color: "#20BEFF",
    courseCount: "15+",
    category: "Data Science",
    url: "https://www.classcentral.com/provider/kaggle",
    features: ["Google-owned platform", "Real-world datasets", "Jupyter notebooks", "Community competitions"],
    courses: [
      { name: "Python", url: "https://www.classcentral.com/course/python-74248" },
      { name: "Intro to Machine Learning", url: "https://www.classcentral.com/course/intro-to-machine-learning-74249" },
      { name: "Intro to Deep Learning", url: "https://www.classcentral.com/course/intro-to-deep-learning-74256" },
      { name: "Intro to SQL", url: "https://www.classcentral.com/course/intro-to-sql-74254" },
      { name: "Computer Vision", url: "https://www.classcentral.com/course/computer-vision-74257" },
      { name: "Data Visualization", url: "https://www.classcentral.com/course/data-visualization-74252" },
    ]
  },
  {
    id: "tasmania",
    name: "University of Tasmania",
    description: "Free certificate courses on dementia, multiple sclerosis, traumatic brain injury, Parkinson's, and other health topics.",
    logo: "https://www.classcentral.com/images/logos/providers/utas-sq.png",
    color: "#FDB913",
    courseCount: "10+",
    category: "Healthcare",
    url: "https://www.classcentral.com/university/utas",
    features: ["Top-rated health courses", "14K+ ratings on Understanding Dementia", "Free certificates", "Expert-led content"],
    courses: [
      { name: "Understanding Dementia", url: "https://www.classcentral.com/course/independent-understanding-dementia-981" },
      { name: "Preventing Dementia", url: "https://www.classcentral.com/course/independent-preventing-dementia-6565" },
      { name: "Understanding Multiple Sclerosis (MS)", url: "https://www.classcentral.com/course/independent-understanding-multiple-sclerosis-ms-13338" },
      { name: "Understanding Traumatic Brain Injury", url: "https://www.classcentral.com/course/independent-understanding-traumatic-brain-injury-mooc-39253" },
      { name: "Parkinson's MOOC", url: "https://www.classcentral.com/course/parkinsons-mooc-429354" },
    ]
  },
  {
    id: "hackerrank",
    name: "HackerRank",
    description: "24 skills certification tests in programming languages and problem solving. Earn certificates in Python, Java, JavaScript, SQL, and more.",
    logo: "https://www.classcentral.com/images/logos/providers/hackerrank-sq.png",
    color: "#00EA64",
    courseCount: "24",
    category: "Programming",
    url: "https://www.hackerrank.com/skills-verification",
    features: ["Employer-recognized", "Coding assessment platform", "Multiple languages", "Shareable certificates"],
    courses: [
      { name: "Problem Solving (Basic)", url: "https://www.hackerrank.com/skills-verification/problem_solving_basic" },
      { name: "Python (Basic) Certification", url: "https://www.hackerrank.com/skills-verification/python_basic" },
      { name: "JavaScript (Basic) Certification", url: "https://www.hackerrank.com/skills-verification/javascript_basic" },
      { name: "SQL (Basic) Certification", url: "https://www.hackerrank.com/skills-verification/sql_basic" },
      { name: "Java (Basic) Certification", url: "https://www.hackerrank.com/skills-verification/java_basic" },
      { name: "Go (Basic) Certification", url: "https://www.hackerrank.com/skills-verification/golang_basic" },
    ]
  },
  {
    id: "helsinki-reaktor",
    name: "University of Helsinki",
    description: "Academic online courses with free certificates including Elements of AI, Full Stack Open, Java Programming, and Ethics of AI.",
    logo: "https://www.classcentral.com/images/logos/providers/helsinki-sq.png",
    color: "#002F6C",
    courseCount: "4+",
    category: "Computer Science",
    url: "https://www.classcentral.com/university/helsinki",
    features: ["Top Finnish university", "Highly-rated courses", "Free certificates", "Practical projects"],
    courses: [
      { name: "Elements of AI", url: "https://www.classcentral.com/course/independent-elements-of-ai-12469" },
      { name: "Full Stack Open", url: "https://www.classcentral.com/course/fullstackopen-deep-dive-into-modern-web-development-66418" },
      { name: "Java Programming", url: "https://www.classcentral.com/course/mooc-fi-java-programming-89476" },
      { name: "Ethics of AI", url: "https://www.classcentral.com/course/helsinki-ethics-of-ai-98596" },
    ]
  },
  {
    id: "hubspot",
    name: "HubSpot Academy",
    description: "26 free courses with certificates covering inbound marketing, sales, content marketing, SEO, social media, and email marketing.",
    logo: "https://www.classcentral.com/images/logos/providers/hubspot-sq.png",
    color: "#FF7A59",
    courseCount: "26",
    category: "Digital Marketing",
    url: "https://www.classcentral.com/provider/hubspot-academy?free-certificate=true",
    features: ["Industry-standard certifications", "Comprehensive marketing training", "Free forever", "Practical skills"],
    courses: [
      { name: "Inbound Marketing", url: "https://www.classcentral.com/course/hubspot-inbound-marketing-course-98574" },
      { name: "Content Marketing", url: "https://www.classcentral.com/course/content-marketing-66297" },
      { name: "SEO Certification", url: "https://www.classcentral.com/course/seo-training-66293" },
      { name: "Social Media Marketing", url: "https://www.classcentral.com/course/social-media-66291" },
      { name: "Email Marketing", url: "https://www.classcentral.com/course/hubspot-email-marketing-course-get-certified-in-email-marketing-98576" },
      { name: "Digital Advertising", url: "https://www.classcentral.com/course/digital-advertising-66244" },
    ]
  },
  {
    id: "saylor",
    name: "Saylor Academy",
    description: "130+ college-level courses with free certificates in History, Business, Chemistry, Economics, Computer Science, and more.",
    logo: "https://www.classcentral.com/images/logos/providers/saylor-sq.png",
    color: "#1A5276",
    courseCount: "130+",
    category: "Academic",
    url: "https://www.classcentral.com/provider/saylor-academy?free-certificate=true",
    features: ["College-level courses", "Free final exam", "70% pass threshold", "Wide subject range"],
    courses: [
      { name: "C++ Programming", url: "https://www.classcentral.com/course/saylor-academy-65-cs107-c-programming-99526" },
      { name: "Elementary Data Structures", url: "https://www.classcentral.com/course/saylor-academy-66-cs201-elementary-data-structure-99528" },
      { name: "Introduction to Supply Chain Management", url: "https://www.classcentral.com/course/saylor-academy-434-prdv304-introduction-to-supply-99624" },
      { name: "Introduction to Java and OOP", url: "https://www.classcentral.com/course/saylor-academy-448-prdv410-introduction-to-java-a-99625" },
    ]
  },
  {
    id: "wolfram",
    name: "Wolfram U",
    description: "40+ free courses with certificates in programming, mathematics, data science, machine learning, and signal processing.",
    logo: "https://www.classcentral.com/images/logos/providers/wolfram-sq.png",
    color: "#DD1100",
    courseCount: "40+",
    category: "Technology",
    url: "https://www.classcentral.com/report/wolfram-u-free-certificates/",
    features: ["Wolfram Language training", "Interactive courses", "Mathematics focus", "Data science courses"],
    courses: [
      { name: "Introduction to Wolfram Language", url: "https://www.classcentral.com/course/wolfram-u-wolfram-language-an-elementary-introduction-to-the-wolfram-language-292967" },
      { name: "Introduction to Calculus", url: "https://www.classcentral.com/course/wolfram-u-mathematics-introduction-to-calculus-292970" },
      { name: "Visual Explorations in Data Science", url: "https://www.classcentral.com/course/wolfram-u-data-science-visual-explorations-in-data-science-292984" },
      { name: "Introduction to Image Processing", url: "https://www.classcentral.com/course/wolfram-u-image-signal-processing-introduction-to-image-processing-293012" },
    ]
  },
  {
    id: "santander",
    name: "Santander Open Academy",
    description: "40+ free online courses with completion certificates in business, technology, marketing, and professional development.",
    logo: "https://www.classcentral.com/images/logos/providers/santander-sq.png",
    color: "#EC0000",
    courseCount: "40+",
    category: "Professional Development",
    url: "https://www.santanderopenacademy.com/en/courses-quick-access.html",
    features: ["Multi-language courses", "Business focus", "Free certificates", "Professional skills"],
    courses: [
      { name: "Introduction to Generative AI", url: "https://www.santanderopenacademy.com/en/courses/generative-artificial-intelligence.html" },
      { name: "Effective Business Writing", url: "https://www.santanderopenacademy.com/en/courses/effective-business-writing.html" },
      { name: "Cloud Computing Course", url: "https://www.santanderopenacademy.com/en/courses/cloud.html" },
      { name: "Mindfulness & Work-life Balance", url: "https://www.santanderopenacademy.com/en/courses/mindfulness.html" },
      { name: "Marketing Automation Fundamentals", url: "https://www.santanderopenacademy.com/en/courses/marketing-automation.html" },
    ]
  },
  {
    id: "cisco",
    name: "CISCO Networking Academy",
    description: "Free self-paced courses with badges in cybersecurity, IoT, Python programming, computer hardware, and operating systems.",
    logo: "https://www.classcentral.com/images/logos/providers/cisco-sq.png",
    color: "#1BA0D7",
    courseCount: "10+",
    category: "Technology",
    url: "https://www.netacad.com/catalogs/learn/information-technology",
    features: ["Industry leader in networking", "Free digital badges", "Self-paced learning", "Hands-on labs"],
    courses: [
      { name: "Introduction to Cybersecurity", url: "https://www.classcentral.com/course/cisco-introduction-to-cybersecurity-97415" },
      { name: "Introduction to IoT", url: "https://www.classcentral.com/course/networking-academy-introduction-to-iot-97417" },
      { name: "PCAP: Programming Essentials in Python", url: "https://www.classcentral.com/course/networking-academy-pcap-programming-essentials-in-python-97421" },
      { name: "Computer Hardware Basics", url: "https://www.netacad.com/courses/computer-hardware-basics?courseLang=en-US" },
      { name: "Operating Systems Basics", url: "https://www.netacad.com/courses/operating-systems-basics?courseLang=en-US" },
    ]
  },
  {
    id: "un-ccelearn",
    name: "UN CC:e-Learn",
    description: "116 free courses with certificates on climate change, sustainability, green economy, and environmental topics from the United Nations.",
    logo: "https://www.classcentral.com/images/logos/providers/un-sq.png",
    color: "#009EDB",
    courseCount: "116",
    category: "Environment",
    url: "https://unccelearn.org/courses/",
    features: ["United Nations courses", "Multi-language", "Climate change focus", "Free certificates"],
    courses: [
      { name: "Gender and Environment", url: "https://www.classcentral.com/course/un-cc-e-learn-gender-and-environment-116565" },
      { name: "Sustainable Diet", url: "https://www.classcentral.com/course/un-cc-e-learn-sustainable-diet-116560" },
      { name: "Cities and Climate Change", url: "https://www.classcentral.com/course/un-cc-e-learn-cities-and-climate-change-116573" },
      { name: "Introduction to Sustainable Finance", url: "https://www.classcentral.com/course/un-cc-e-learn-introduction-to-sustainable-finance-116566" },
      { name: "Children and Climate Change", url: "https://www.classcentral.com/course/un-cc-e-learn-children-and-climate-change-116572" },
    ]
  },
  {
    id: "edraak",
    name: "Edraak",
    description: "185 free courses and specializations with free certificates in Arabic covering technology, business, science, and professional skills.",
    logo: "https://www.classcentral.com/images/logos/providers/edraak-sq.png",
    color: "#00A3E0",
    courseCount: "185",
    category: "Academic",
    url: "https://www.edraak.org/courses/",
    features: ["Arabic-language platform", "Free certificates", "Wide subject range", "Top Arab universities"],
    courses: [
      { name: "CV Writing", url: "https://www.classcentral.com/course/edraak-lsyr-lth-ty-ln-gh-2045" },
      { name: "Introduction to Computer Science - CS50x", url: "https://www.edraak.org/programs/course-v1:edraak+CS50+T2_2020/" },
      { name: "Advanced Excel Skills", url: "https://www.edraak.org/programs/course-v1:Edraak+AE101+SP-2019/" },
      { name: "Agile Methodology Applications", url: "https://www.edraak.org/programs/course-v1:edraak+Agile101+T1_2020/" },
    ]
  },
  {
    id: "fao",
    name: "FAO elearning Academy",
    description: "100+ free courses on food security, agriculture, sustainable development, and natural resource management from the UN Food and Agriculture Organization.",
    logo: "https://www.classcentral.com/images/logos/providers/fao-sq.png",
    color: "#5B8C2A",
    courseCount: "100+",
    category: "Agriculture",
    url: "https://elearning.fao.org/mod/page/view.php?id=4534",
    features: ["UN FAO courses", "Digital Badge certification", "Food security focus", "Multi-language"],
    courses: [
      { name: "Sustainable Food Systems: Concept and Framework", url: "https://elearning.fao.org/course/view.php?id=738" },
      { name: "International Trade in Fisheries", url: "https://elearning.fao.org/course/view.php?id=949" },
      { name: "Managing Climate Risks through Social Protection", url: "https://elearning.fao.org/course/view.php?id=744" },
      { name: "Sharing Forests MOOC", url: "https://elearning.fao.org/local/search/infocourse.php?id=746" },
    ]
  },
  {
    id: "acumen",
    name: "Acumen Academy",
    description: "30 free courses on social change, leadership, human-centered design, systems thinking, and social entrepreneurship.",
    logo: "https://www.classcentral.com/images/logos/providers/acumen-sq.png",
    color: "#FDBB30",
    courseCount: "30",
    category: "Social Impact",
    url: "https://acumenacademy.org/courseCatalog/",
    features: ["Social impact focus", "Statement of Accomplishment", "Expert instructors", "Practical skills"],
    courses: [
      { name: "Systems Practice", url: "https://www.classcentral.com/course/acumen-academy-systems-practice-8853" },
      { name: "Social Entrepreneurship 101", url: "https://www.classcentral.com/course/acumen-academy-social-entrepreneurship-101-3665" },
      { name: "Adaptive Leadership", url: "https://www.classcentral.com/course/acumen-academy-adaptive-leadership-1824" },
      { name: "Introduction to Human-Centered Design", url: "https://www.classcentral.com/course/acumen-academy-introduction-to-human-centered-design-1823" },
      { name: "Storytelling for Change", url: "https://www.classcentral.com/course/acumen-academy-storytelling-for-change-1559" },
    ]
  },
  {
    id: "hugging-face",
    name: "Hugging Face",
    description: "Free courses with certificates on AI agents, deep reinforcement learning, computer vision, audio processing, and the Model Context Protocol.",
    logo: "https://www.classcentral.com/images/logos/providers/huggingface-sq.png",
    color: "#FFD21E",
    courseCount: "5+",
    category: "AI & ML",
    url: "https://huggingface.co/learn",
    features: ["Cutting-edge AI topics", "Hands-on learning", "Community-driven", "Free certificates"],
    courses: [
      { name: "AI Agents Course", url: "https://huggingface.co/learn/agents-course/unit0/introduction" },
      { name: "Deep Reinforcement Learning", url: "https://huggingface.co/learn/deep-rl-course/unit0/introduction" },
      { name: "Community Computer Vision", url: "https://huggingface.co/learn/computer-vision-course/unit0/welcome/welcome" },
      { name: "Audio Course", url: "https://huggingface.co/learn/audio-course/chapter0/introduction" },
      { name: "Model Context Protocol (MCP)", url: "https://huggingface.co/learn/mcp-course/unit0/introduction" },
    ]
  },
  {
    id: "stepik",
    name: "Stepik",
    description: "100 free courses with certificates in programming, computer science, and mathematics. Available in Russian and English.",
    logo: "https://www.classcentral.com/images/logos/providers/stepik-sq.png",
    color: "#2D9CDB",
    courseCount: "100",
    category: "Programming",
    url: "https://stepik.org/catalog/search?cert=true&free=true",
    features: ["Interactive learning", "Russian & English", "Programming focus", "Free certificates"],
    courses: [
      { name: "Programming in Python", url: "https://stepik.org/course/67/promo" },
      { name: "Python: Basics and Applications", url: "https://stepik.org/course/512/promo" },
      { name: "Interactive SQL Trainer", url: "https://stepik.org/course/63054/promo" },
      { name: "Introduction to Programming (C++)", url: "https://stepik.org/course/363/promo" },
    ]
  },
  {
    id: "upgrad",
    name: "upGrad",
    description: "100+ free programs and courses with e-Certificates of Completion in data science, business analytics, technology, and more.",
    logo: "https://www.classcentral.com/images/logos/providers/upgrad-sq.png",
    color: "#FF6B35",
    courseCount: "100+",
    category: "Professional Development",
    url: "https://www.upgrad.com/cn/free-courses/",
    features: ["Indian edtech leader", "Free e-certificates", "Data science focus", "Industry-relevant"],
    courses: [
      { name: "Programming with Python for Beginners", url: "https://www.upgrad.com/au/free-courses/data-science/programming-with-python-course-for-beginners-free/" },
      { name: "Introduction to Natural Language Processing", url: "https://www.upgrad.com/au/free-courses/data-science/introduction-to-natural-language-processing-free-course/" },
      { name: "Introduction to Data Analysis using Excel", url: "https://www.upgrad.com/au/free-courses/data-science/excel-for-data-analysis-course-free/" },
      { name: "Fundamentals of Deep Learning", url: "https://www.upgrad.com/au/free-courses/data-science/fundamentals-of-deep-learning-neural-networks-free-course/" },
    ]
  },
  {
    id: "savealife",
    name: "Save A Life by NHCPS",
    description: "6 free first aid training courses with free completion certificates including ACLS, PALS, BLS, CPR, and Bloodborne Pathogens.",
    logo: "https://www.classcentral.com/images/logos/providers/nhcps-sq.png",
    color: "#E74C3C",
    courseCount: "6",
    category: "Healthcare",
    url: "https://nhcps.com/",
    features: ["Life-saving skills", "Free certificates", "Optional certification exams", "Medical training"],
    courses: [
      { name: "Advanced Cardiac Life Support (ACLS)", url: "https://nhcps.com/course/acls-advanced-cardiac-life-support-certification-course/" },
      { name: "Pediatric Advanced Life Support (PALS)", url: "https://nhcps.com/course/pals-pediatric-advanced-life-support-certification-course/" },
      { name: "Basic Life Support (BLS)", url: "https://nhcps.com/course/bls-basic-life-support-certification-course/" },
      { name: "CPR, AED & First Aid", url: "https://nhcps.com/course/cpr-aed-first-aid-certification-course/" },
      { name: "Bloodborne Pathogens", url: "https://nhcps.com/course/bloodborne-pathogens-certification-course/" },
    ]
  },
  {
    id: "complexity-explorer",
    name: "Complexity Explorer",
    description: "5 self-paced courses with free certificates on complexity science, dynamical systems, fractals, and nonlinear dynamics.",
    logo: "https://www.classcentral.com/images/logos/providers/sfi-sq.png",
    color: "#8E44AD",
    courseCount: "5",
    category: "Science",
    url: "https://www.complexityexplorer.org/courses",
    features: ["Santa Fe Institute", "Complexity science", "Self-paced", "70% pass threshold"],
    courses: [
      { name: "Introduction to Complexity", url: "https://www.complexityexplorer.org/courses/185-introduction-to-complexity" },
      { name: "Introduction to Dynamical Systems and Chaos", url: "https://www.complexityexplorer.org/courses/186-introduction-to-dynamical-systems-and-chaos" },
      { name: "Fractals and Scaling", url: "https://www.complexityexplorer.org/courses/187-fractals-and-scaling" },
      { name: "Origins of Life", url: "https://www.complexityexplorer.org/courses/170-origins-of-life" },
    ]
  },
  {
    id: "ec-council",
    name: "EC-Council",
    description: "9 free cybersecurity courses with certificates covering cloud computing, bug bounty hunting, dark web, SQL injection, and more.",
    logo: "https://www.classcentral.com/images/logos/providers/eccouncil-sq.png",
    color: "#2C3E50",
    courseCount: "9",
    category: "Cybersecurity",
    url: "https://www.eccouncil.org/cybersecurity-exchange/cyber-novice/free-cybersecurity-courses-beginners/",
    features: ["Cybersecurity focus", "Free certificates", "Hands-on labs", "Industry-recognized"],
    courses: [
      { name: "A Practical Introduction to Cloud Computing", url: "https://codered.eccouncil.org/course/a-practical-introduction-to-cloud-computing" },
      { name: "Introduction to Dark Web, Anonymity, and Cryptocurrency", url: "https://codered.eccouncil.org/course/introduction-to-dark-web-anonymity-and-cryptocurrency" },
      { name: "SQL Injection Attacks", url: "https://codered.eccouncil.org/course/sql-injection-attacks" },
      { name: "Android Bug Bounty Hunting", url: "https://codered.eccouncil.org/course/android-bug-bounty-hunting-hunt-like-a-rat" },
    ]
  },
  {
    id: "openhpi",
    name: "openHPI",
    description: "Self-paced courses with free certificates in data science, NLP, Bayesian statistics, and quantum computing from Hasso Plattner Institute.",
    logo: "https://www.classcentral.com/images/logos/providers/openhpi-sq.png",
    color: "#0077B6",
    courseCount: "10+",
    category: "Computer Science",
    url: "https://open.hpi.de/courses",
    features: ["German excellence", "English & German courses", "Free participation certificates", "Achievement certificates"],
    courses: [
      { name: "Understanding Embeddings for NLP", url: "https://open.hpi.de/courses/embeddingsfornlp-kisz2023" },
      { name: "Data Science Bootcamp", url: "https://open.hpi.de/courses/datascience2023" },
      { name: "Introduction to Bayesian Data Analysis", url: "https://open.hpi.de/courses/bayesian-statistics2023" },
      { name: "Introduction to Quantum Computing with Qiskit", url: "https://open.hpi.de/courses/qc-qiskit2022" },
    ]
  },
  {
    id: "marginal-revolution",
    name: "Marginal Revolution University",
    description: "18 free economics courses and series with certificates covering microeconomics, macroeconomics, development, and international trade.",
    logo: "https://www.classcentral.com/images/logos/providers/mru-sq.png",
    color: "#2E86C1",
    courseCount: "18",
    category: "Economics",
    url: "https://mru.org/learn",
    features: ["Economics focus", "Free certificates", "Expert economists", "Video-based learning"],
    courses: [
      { name: "Principles of Economics: Microeconomics", url: "https://www.classcentral.com/course/mru-principles-of-economics-microeconomics-98198" },
      { name: "Principles of Economics: Macroeconomics", url: "https://www.classcentral.com/course/mru-principles-of-economics-macroeconomics-98199" },
      { name: "Development Economics", url: "https://www.classcentral.com/course/mru-development-economics-98206" },
      { name: "International Trade", url: "https://www.classcentral.com/course/mru-international-trade-98256" },
    ]
  },
  {
    id: "twitter",
    name: "X (Twitter) Marketing",
    description: "Free badges for advertising and marketing on X (Twitter) through X Ads Academy. Earn badges by scoring 80%+ on assessments.",
    logo: "https://www.classcentral.com/images/logos/providers/twitter-sq.png",
    color: "#1DA1F2",
    courseCount: "3+",
    category: "Digital Marketing",
    url: "https://www.xadsacademy.com/student/catalog",
    features: ["Free digital badges", "Social media marketing", "Practical advertising skills", "Self-paced"],
    courses: [
      { name: "Ads Manager Fundamentals", url: "https://www.xadsacademy.com/student/path/1120386-ads-manager-fundamentals" },
      { name: "Mobile App Campaigns", url: "https://www.xadsacademy.com/student/path/1738354-mobile-app-campaign-badge" },
      { name: "Website Traffic & Sales Campaigns", url: "https://www.xadsacademy.com/student/path/1288857-website-traffic-sales-campaigns" },
    ]
  },
  {
    id: "philanthropyu",
    name: "Philanthropy University",
    description: "20 free courses with certificates in branding, fundraising, monitoring & evaluation, theory of change, and nonprofit management.",
    logo: "https://www.classcentral.com/images/logos/providers/philanthropyu-sq.png",
    color: "#E67E22",
    courseCount: "20",
    category: "Nonprofit",
    url: "https://courses.philanthropyu.org/courses",
    features: ["Nonprofit focus", "Free certificates", "Practical skills", "50% pass threshold"],
    courses: [
      { name: "Branding 101", url: "https://www.classcentral.com/course/independent-branding-101-21019" },
      { name: "Fundraising: Connecting with Donors", url: "https://courses.philanthropyu.org/courses/course-v1:PhilanthropyU+Fundraising_201+13_2.4_20191223_ondemand/about" },
      { name: "Creating a Theory of Change", url: "https://courses.philanthropyu.org/courses/course-v1:PhilanthropyU+TheoryChange_101+3_2.4_20191223_ondemand/about" },
      { name: "Developing an Operating Budget", url: "https://courses.philanthropyu.org/courses/course-v1:PhilanthropyU+Budget_000+4_3.11_20200717_ondemand/about" },
    ]
  },
  {
    id: "itcilo",
    name: "ITCILO",
    description: "50 free courses on sustainable enterprise development, labor laws, gender equality, and workplace safety from the International Training Centre of the ILO.",
    logo: "https://www.classcentral.com/images/logos/providers/itcilo-sq.png",
    color: "#003366",
    courseCount: "50",
    category: "Professional Development",
    url: "https://www.itcilo.org/courses",
    features: ["UN agency courses", "Multi-language", "Labor & workplace focus", "Free certificates"],
    courses: [
      { name: "Introduction to International Labour Standards", url: "https://www.itcilo.org/courses/introduction-international-labour-standards" },
      { name: "Disability in the Workplace", url: "https://www.itcilo.org/courses/disability-workplace" },
      { name: "Fire Safety Management", url: "https://www.itcilo.org/courses/fire-safety-management" },
      { name: "The Future of Work in the Rural Economy", url: "https://www.itcilo.org/courses/future-work-rural-economy" },
    ]
  },
  {
    id: "bayern",
    name: "Virtuelle Hochschule Bayern",
    description: "100+ free courses in German and English from Bavarian universities with free certificates on various academic subjects.",
    logo: "https://www.classcentral.com/images/logos/providers/vhb-sq.png",
    color: "#004D99",
    courseCount: "100+",
    category: "Academic",
    url: "https://open.vhb.org/kursliste",
    features: ["Bavarian universities", "German & English", "Academic courses", "70-80% pass threshold"],
    courses: [
      { name: "Flourishing Together: Team Health in Hybrid Work", url: "https://open.vhb.org/blocks/occoursemetaselect/detailpage.php?id=348" },
      { name: "Principles of Fintech Business Models", url: "https://open.vhb.org/blocks/occoursemetaselect/detailpage.php?id=312" },
      { name: "Building Confidence in Statistics", url: "https://open.vhb.org/blocks/occoursemetaselect/detailpage.php?id=323" },
    ]
  },
  {
    id: "dlthub",
    name: "dltHub",
    description: "6 free courses with certificates on data engineering, dlt pipelines, agentic data engineering, and Snowflake integration.",
    logo: "https://www.classcentral.com/images/logos/providers/dlthub-sq.png",
    color: "#00B4D8",
    courseCount: "6",
    category: "Data Engineering",
    url: "https://dlthub.learnworlds.com/courses",
    features: ["Data engineering focus", "Hands-on learning", "Free certificates", "Modern data stack"],
    courses: [
      { name: "dlt Fundamentals", url: "https://dlthub.learnworlds.com/course/dlt-fundamentals" },
      { name: "dlt Advanced", url: "https://dlthub.learnworlds.com/course/dlt-advanced" },
      { name: "Agentic Data Engineering with dltHub", url: "https://dlthub.learnworlds.com/course/agentic-data-engineering" },
      { name: "Deploy dlt Pipelines", url: "https://dlthub.learnworlds.com/course/deploy-dlt-pipeline" },
    ]
  },
  {
    id: "watershed",
    name: "Watershed Academy (EPA)",
    description: "Free Watershed Management Training Certificate from the US EPA. Complete 15 modules on watershed ecology, management, and community practices.",
    logo: "https://www.classcentral.com/images/logos/providers/epa-sq.png",
    color: "#2E86C1",
    courseCount: "15 modules",
    category: "Environment",
    url: "https://www.epa.gov/watershedacademy/watershed-academy-web-training-certificate",
    features: ["US EPA program", "Environmental focus", "Comprehensive training", "Free certificate"],
    courses: [
      { name: "Watershed Management Training Certificate", url: "https://www.epa.gov/watershedacademy/online-training-watershed-management" },
    ]
  },
  {
    id: "global-campus-human-rights",
    name: "Global Campus of Human Rights",
    description: "Free MOOCs on human rights with certificates of completion. Promoting and Protecting Human Rights: A Global Overview.",
    logo: "https://www.classcentral.com/images/logos/providers/gchumanrights-sq.png",
    color: "#C0392B",
    courseCount: "5+",
    category: "Social Impact",
    url: "https://www.gchumanrights.org/training-and-courses/",
    features: ["Human rights focus", "Global perspective", "Free enrollment", "Certificate of Completion"],
    courses: [
      { name: "Promoting and Protecting Human Rights", url: "https://elearning.gchumanrights.org/courses/course-v1:gchumanrights+pphr+2020/" },
    ]
  },
  {
    id: "urbino",
    name: "University of Urbino",
    description: "10 free courses with certificates and badges in Italian covering AI, intercultural communication, coding, and digital platforms.",
    logo: "https://www.classcentral.com/images/logos/providers/urbino-sq.png",
    color: "#8E44AD",
    courseCount: "10",
    category: "Academic",
    url: "https://mooc.uniurb.it/wp/all-courses/",
    features: ["Italian university", "Free certificates & badges", "Italian language", "Diverse topics"],
    courses: [
      { name: "Intelligenza Artificiale", url: "https://www.classcentral.com/course/urbino-intelligenza-artificiale-97425" },
      { name: "Coding per Genitori", url: "https://www.classcentral.com/course/urbino-coding-per-genitori-97427" },
    ]
  },
];

export const categories = [
  { id: "all", name: "All Providers", icon: "🎓" },
  { id: "Programming", name: "Programming & Coding", icon: "💻" },
  { id: "Technology", name: "Technology & Cloud", icon: "☁️" },
  { id: "Digital Marketing", name: "Digital Marketing", icon: "📊" },
  { id: "Data Science", name: "Data Science & AI", icon: "🤖" },
  { id: "Academic", name: "Academic & University", icon: "🏛️" },
  { id: "Healthcare", name: "Healthcare & Medicine", icon: "🏥" },
  { id: "Professional Development", name: "Professional Development", icon: "📈" },
  { id: "Environment", name: "Environment & Climate", icon: "🌿" },
  { id: "Social Impact", name: "Social Impact & Nonprofit", icon: "🤝" },
  { id: "Cybersecurity", name: "Cybersecurity", icon: "🔒" },
  { id: "Engineering", name: "Engineering & Science", icon: "🔬" },
  { id: "Economics", name: "Economics & Business", icon: "💰" },
  { id: "Agriculture", name: "Agriculture & Food", icon: "🌾" },
  { id: "Data Engineering", name: "Data Engineering", icon: "⚙️" },
  { id: "Nonprofit", name: "Nonprofit & Philanthropy", icon: "❤️" },
  { id: "Computer Science", name: "Computer Science", icon: "🖥️" },
  { id: "AI & ML", name: "AI & Machine Learning", icon: "🧠" },
  { id: "Science", name: "Science & Mathematics", icon: "🔬" },
];
